version: '3.8'

services:
  api:
    build: .
    ports:
      - "0.0.0.0:8000:8000"
    environment:
      - DB_HOST=34.55.144.7
      - DB_PORT=5432
      - DB_USER=mlb
      - DB_PASSWORD=mlb
      - DB_NAME=mlb-app
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_SEARCH_ENGINE_ID=${GOOGLE_SEARCH_ENGINE_ID}
    volumes:
      - ./app:/app/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

volumes:
  cloudsql: 