version: '3.8'

services:
  api:
    build: .
    ports:
      - "0.0.0.0:443:443"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_SEARCH_ENGINE_ID=${GOOGLE_SEARCH_ENGINE_ID}
    volumes:
      - ./app:/app/app
      - ./ssl:/app/ssl  # Mount SSL certificates
    restart: unless-stopped

volumes:
  cloudsql: 