name: Deploy Frontend

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: mlb-hackathon-448420
  REGION: us-central1

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Clean up old builds
      run: |
        # Remove old build artifacts
        rm -rf build/
        rm -rf node_modules/
        
        # Only try to clean up if we have access
        if gcloud projects describe ${{ env.PROJECT_ID }} &>/dev/null; then
          # Clean up old Cloud Build artifacts
          gcloud container images list-tags gcr.io/${{ env.PROJECT_ID }}/mlb-app \
            --format='get(digest)' --filter='timestamp.datetime < -P30D' | \
          while read digest; do
            gcloud container images delete "gcr.io/${{ env.PROJECT_ID }}/mlb-app@${digest}" --quiet --force-delete-tags
          done || true
          
          # Clean up old Cloud Run revisions
          gcloud run revisions list \
            --platform managed \
            --region ${{ env.REGION }} \
            --service mlb-app \
            --format="get(metadata.name)" \
            --filter="metadata.creationTimestamp < -P30D" | \
          while read revision; do
            gcloud run revisions delete $revision --quiet --region ${{ env.REGION }}
          done || true
        fi

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        project_id: ${{ env.PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Submit Cloud Build
      run: |
        gcloud builds submit --config cloudbuild.yaml --project ${{ env.PROJECT_ID }} --async
        sleep 10
        BUILD_STATUS=$(gcloud builds list --limit=1 --format="get(status)")
        echo "Latest build status: $BUILD_STATUS"
        BUILD_ID=$(gcloud builds list --limit=1 --format="get(id)")
        echo "Build URL: https://console.cloud.google.com/cloud-build/builds/$BUILD_ID?project=${{ env.PROJECT_ID }}" 