name: CI/CD to Google Cloud

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: mlb-hackathon-448420
  REGION: us-central1

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ env.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Authenticate with Google Cloud
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > /tmp/key.json
        gcloud auth activate-service-account --key-file=/tmp/key.json

    - name: Submit Cloud Build
      run: |
        gcloud builds submit --config cloudbuild.yaml --project ${{ env.PROJECT_ID }} 