name: CI/CD to Google Cloud

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: mlb-hackathon-448420
  REGION: us-central1

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        project_id: ${{ env.PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Submit Cloud Build
      run: |
        gcloud builds submit --config cloudbuild.yaml --project ${{ env.PROJECT_ID }} 