name: CI/CD to Google Cloud

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: mlb-hackathon-448420
  REGION: us-central1

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Docker
      run: |
        # Update package list
        sudo apt-get update
        
        # Install Docker dependencies
        sudo apt-get install -y \
          apt-transport-https \
          ca-certificates \
          curl \
          gnupg \
          lsb-release

        # Add Docker's official GPG key
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

        # Set up stable repository
        echo \
          "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

        # Install Docker
        sudo apt-get update
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io

        # Add runner user to docker group
        sudo usermod -aG docker $USER

    - name: Clean up old builds
      run: |
        # Remove old build artifacts
        rm -rf build/
        rm -rf node_modules/
        
        # Clean Docker images and containers
        sudo docker system prune -af
        
        # Clean up old Cloud Build artifacts
        gcloud container images list-tags gcr.io/${{ env.PROJECT_ID }}/mlb-app \
          --format='get(digest)' --filter='timestamp.datetime < -P30D' | \
        while read digest; do
          gcloud container images delete "gcr.io/${{ env.PROJECT_ID }}/mlb-app@${digest}" --quiet
        done || true

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        project_id: ${{ env.PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Submit Cloud Build
      run: |
        gcloud builds submit --config cloudbuild.yaml --project ${{ env.PROJECT_ID }} 